### PR TITLE
Add support for multiple wildcard domains

### PR DESCRIPTION
**Pull request by jeffreylo**
This patch adds support for a comma-separated list of domains for
DNS_DOMAIN.

### CODE REVIEW

**Comment by jeffreylo** [comment]
tumbleweed

**Comment by jeffreylo** [comment]
tumbleweed

**Comment by jeffreylo** [comment]
tumbleweed

**Comment by jeffreylo** [comment]
tumbleweed

**Comment by ruudud** [comment]
Hmm.. what's the use case for this?

**Comment by jeffreylo** [comment]
I’ve got a set of projects at work with different TLDs; it’d be useful to open this up as a configurable option. That said, feel free to close if it’s not in the spirit of the project. :)

**Pull request closed without merging**
